name: publish
on: push

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: ./.github/actions/setup-depot_tools

    - run: mkdir devtools
    - run: fetch devtools-frontend
      working-directory: ./devtools
    - run: git checkout << ${{ github.workspace }}/devtools-frontend.commit
      working-directory: ./devtools/devtools-frontend
    - run: gclient sync
      working-directory: ./devtools/devtools-frontend
    - run: git apply ${{ github.workspace }}/patches/add-timeline_export_app.patch
      working-directory: ./devtools/devtools-frontend
    - run: git apply ${{ github.workspace }}/patches/adapt-timeline-panel-ux.patch
      working-directory: ./devtools/devtools-frontend
    - run: gn gen out/Default
      working-directory: ./devtools/devtools-frontend
    - run: autoninja -C out/Default
      working-directory: ./devtools/devtools-frontend

    - uses: actions/setup-node@v1
      with:
        version: 12.x

    - run: node ${{ github.workspace }}/scripts/create-manifest.js front_end/timeline_export_app.json > out/Default/resources/inspector/package.json
      working-directory: ./devtools/devtools-frontend
      env:
        GITHUB_RUN_ID: ${{ github.run_id }}

    - run: npm publish --access=public
      working-directory: ./devtools/devtools-frontend/out/Default/resources/inspector
      continue-on-error: true
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
