name: create-and-publish
on: push


jobs:
  create:
    runs-on: ubuntu-latest

    steps:
    - run: apt-get update -y
    - run: apt-get install git python clang -y

    - run: rm -rf depot_tools gn devtools
    - run: git clone --depth=1 https://chromium.googlesource.com/chromium/tools/depot_tools.git
    - run: echo "::add-path::${{ github.workspace }}/depot_tools"

    - run: git clone https://gn.googlesource.com/gn
    - run: python build/gen.py
      working-directory: ./gn
    - run: ninja -C out
      working-directory: ./gn
    - run: echo "::add-path::${{ github.workspace }}/gn/out"

    - run: mkdir devtools
    - run: fetch devtools-frontend
      working-directory: ./devtools
    - run: git checkout << ${{ github.workspace }}/devtools-frontend.commit
      working-directory: ./devtools/devtools-frontend
    - run: gclient sync
      working-directory: ./devtools/devtools-frontend
    - run: git apply ${{ github.workspace }}/patches/add-timeline_export_app.patch
      working-directory: ./devtools/devtools-frontend
    - run: git apply ${{ github.workspace }}/patches/adapt-timeline-panel-ux.patch
      working-directory: ./devtools/devtools-frontend
    - run: gn gen out/Default
      working-directory: ./devtools/devtools-frontend
    - run: autoninja -C out/Default
      working-directory: ./devtools/devtools-frontend

    - run: node scripts/create-manifest.js front_end/timeline_export_app.json > out/Default/resources/inspector/package.json
      working-directory: ./devtools/devtools-frontend
      with:
          version: 12.x

  publish:
    runs-on: ubuntu-latest
    needs: create
    steps:
    - run: npm publish
      working-directory: ./devtools/devtools-frontend/out/Default/resources/inspector
      with:
          version: 12.x
          registry-url: 'https://npm.pkg.github.com'
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}